flags:
  send_anonymous_usage_stats: False

dbt_atproto_example:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./bsky_analytics.duckdb
      threads: 4
      attach:
        - path: "https://hive.buz.dev/bluesky/catalog"
          alias: bsky

